name: fs-tool
channels:
  - conda-forge
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python>=3.8
  - pandas
  - numpy
  - scikit-learn
  - pyyaml
  # - rich
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - rnanorm
  - xgboost
  - pip:
      - typing-extensions
      - pydeseq2
