{% set name = "featsel" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../  # Path to your package directory (if building locally)
  # Alternatively, use a URL if the source is hosted online:
  # url: "https://github.com/your-repo-url/archive/v{{ version }}.tar.gz"
  # sha256: <calculated SHA256 checksum of the source tarball>

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pandas
    - typer[all]
    - numpy
    - scikit-learn

about:
  home: "https://github.com/your-repo-url"  # Replace with your GitHub or project homepage
  license: MIT  # Replace with your package's license
  license_family: MIT
  license_file: LICENSE
  summary: "A command-line tool for count data analysis with method selection"
  doc_url: "https://github.com/your-repo-url#readme"  # Documentation link
  dev_url: "https://github.com/your-repo-url"  # Development link

extra:
  recipe-maintainers:
    - eirroer  # Replace with your GitHub username