
count_file: "mock_data_lc/lc_mirna_counts.csv"
metadata_file: "mock_data_lc/lc_dataset.csv"
# count_holdout_test_set: None
# metadata_holdout_test_set: None
 
preprocessing:
  train_test_split_params:
    test_size: 0.2
    random_state: 42

  threshold_filter:
      use_method: True
      min_count: 10
      min_samples: 3

  normalization_methods:
    # - tmm
    # - cpm
    - vst
    # - deseq2

  scaling_methods_metadata: # Use only on metadata
    standard_scale:
      use_method: False
    min_max_scale:
      use_method: False
    max_abs_scale:
      use_method: False

  scaling_methods_count: # Optional scaling on count data
    shrinkage_scaling: # Not implemented
      use_method: False 

  pca:
      use_method: True
      n_components: 2

  pre_filter_methods:
    variance_filter:
      use_method: False
      threshold: 0.5
    expr_percentile_filter:
      use_method: False
      threshold_percentile: 0.8
    correlation_filter:
      use_method: True
      correlation_method: "spearman" # or "pearson", "kendall"
      threshold: 0.9

feature_selection:
  n_cores: 4
  methods:
  - random_forest
  - xgboost